version: '3'
services:
  mysql-server:
    image: mysql:5
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
    volumes:
    - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
    ports:
    - "3306:3306"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-3.4.12
    environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
    depends_on:
    - mysql-server
    volumes:
    - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
    - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    ports:
    - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-3.4.12
    environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
    - "8080:80"
    depends_on:
    - zabbix-server
    volumes:
    - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro

  dockbix-agent-xxl:
    image: monitoringartist/dockbix-agent-xxl-limited:latest
    privileged: true
    volumes:
    - /var/run:/var/run
    - /:/rootfs
    ports:
    - "10050:10050"
    depends_on:
    - zabbix-server
  nginx:
    image: nginx
    ports:
    - "8088:80"

